AuditLogsService:
  Db:
    LogsConnString:
      settings-key: AuditLogsService-LogsConnString
      types:
        - AzureTableStorage
    SqlDbConnString:
      settings-key: AuditLogsService-SqlDbConnString
  Rabbit:
    Publishers:
      ConnectionString:
        settings-key: UserManagmentRabbitMQ
        types:
          - RabbitMq
    Subscribers:
      ConnectionString:
        settings-key: UserManagmentRabbitMQ
        types:
          - RabbitMq
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

